services:
  - type: web
    name: pttkht
    runtime: python
    plan: free
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn quan_ly_phong_kham.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
