# Generated by Django 5.2.8 on 2025-12-18 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoSoBenhAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chan_doan', models.TextField(verbose_name='Chẩn đoán')),
                ('toa_thuoc', models.TextField(verbose_name='Toa thuốc')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('lich_hen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ho_so_benh_an', to='appointments.lichhen', verbose_name='Lịch hẹn')),
            ],
            options={
                'verbose_name': 'Hồ sơ bệnh án',
                'verbose_name_plural': 'Hồ sơ bệnh án',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
