# Generated by Django 5.2.8 on 2025-12-24 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thuoc', models.CharField(max_length=200, verbose_name='Tên thuốc')),
                ('don_vi', models.CharField(default='viên', max_length=50, verbose_name='Đơn vị')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Thuốc',
            },
        ),
        migrations.RemoveField(
            model_name='hosobenhan',
            name='toa_thuoc',
        ),
        migrations.CreateModel(
            name='ToaThuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('ghi_chu', models.CharField(blank=True, max_length=500, verbose_name='Ghi chú')),
                ('ho_so_benh_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toa_thuoc', to='medical_records.hosobenhan', verbose_name='Hồ sơ bệnh án')),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.thuoc', verbose_name='Thuốc')),
            ],
            options={
                'verbose_name': 'Toa thuốc',
                'verbose_name_plural': 'Toa thuốc',
            },
        ),
    ]
