# Generated by Django 5.2.8 on 2025-12-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_thuoc_remove_hosobenhan_toa_thuoc_toathuoc'),
    ]

    operations = [
    ]
