# Generated by Django 5.2.8 on 2026-04-20 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hop_thoai_ai", "0001_initial"),
        ("tai_khoan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedSymptomAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trieu_chung", models.TextField(verbose_name="Triệu chứng gốc")),
                (
                    "trieu_chung_chuan_hoa",
                    models.TextField(
                        db_index=True,
                        help_text="Dạng lowercase + trim để so sánh nhanh",
                        verbose_name="Triệu chứng chuẩn hóa",
                    ),
                ),
                ("do_tin_cay", models.FloatField(verbose_name="Độ tin cậy (%)")),
                (
                    "phan_tich_chi_tiet",
                    models.JSONField(verbose_name="Phân tích chi tiết"),
                ),
                (
                    "phuong_phap",
                    models.CharField(
                        choices=[
                            ("keyword", "Từ khóa"),
                            ("ai", "AI Gemini"),
                            ("keyword_fallback", "Từ khóa (dự phòng)"),
                        ],
                        max_length=20,
                        verbose_name="Phương pháp phân tích",
                    ),
                ),
                (
                    "so_lan_su_dung",
                    models.IntegerField(default=1, verbose_name="Số lần sử dụng"),
                ),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "chuyen_khoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_analyses",
                        to="tai_khoan.chuyenkhoa",
                        verbose_name="Chuyên khoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache phân tích triệu chứng",
                "verbose_name_plural": "Cache phân tích triệu chứng",
                "ordering": ["-so_lan_su_dung", "-ngay_cap_nhat"],
            },
        ),
    ]
