# Generated by Django 5.2.8 on 2026-04-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hop_thoai_ai", "0002_cachedsymptomanalysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedsymptomanalysis",
            name="trieu_chung_chuan_hoa",
            field=models.CharField(
                db_index=True,
                help_text="Dạng lowercase + trim để so sánh nhanh",
                max_length=500,
                verbose_name="Triệu chứng chuẩn hóa",
            ),
        ),
    ]
