# Generated by Django 5.2.8 on 2025-12-18 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenKhoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, verbose_name='Tên chuyên khoa')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Chuyên khoa',
                'verbose_name_plural': 'Chuyên khoa',
            },
        ),
        migrations.CreateModel(
            name='HoSoBacSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('bang_cap', models.CharField(max_length=200, verbose_name='Bằng cấp')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('phi_kham', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Phí khám')),
                ('chuyen_khoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.chuyenkhoa', verbose_name='Chuyên khoa')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ho_so_bac_si', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ bác sĩ',
                'verbose_name_plural': 'Hồ sơ bác sĩ',
            },
        ),
        migrations.CreateModel(
            name='HoSoBenhNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('dia_chi', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ho_so_benh_nhan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ bệnh nhân',
                'verbose_name_plural': 'Hồ sơ bệnh nhân',
            },
        ),
    ]
