# Generated by Django 5.2.8 on 2025-12-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosobacsi',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='bac_si/', verbose_name='Ảnh đại diện'),
        ),
    ]
