# Generated by Django 5.2.8 on 2025-12-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hosobacsi_anh_dai_dien'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosobenhnhan',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='benh_nhan/', verbose_name='Ảnh đại diện'),
        ),
    ]
