# Generated by Django 5.2.8 on 2026-03-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_danhgiabacsi'),
        ('accounts', '0003_hosobenhnhan_anh_dai_dien'),
    ]

    operations = [
    ]
