# Generated by Django 5.2.8 on 2026-04-20 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lich_hen", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThongBao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tieu_de", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("noi_dung", models.TextField(verbose_name="Nội dung")),
                (
                    "loai",
                    models.CharField(
                        choices=[
                            ("lich_hen_moi", "Lịch hẹn mới"),
                            ("xac_nhan", "Xác nhận lịch hẹn"),
                            ("huy", "Hủy lịch hẹn"),
                            ("hoan_thanh", "Hoàn thành khám"),
                            ("he_thong", "Hệ thống"),
                        ],
                        default="he_thong",
                        max_length=20,
                    ),
                ),
                ("da_doc", models.BooleanField(default=False, verbose_name="Đã đọc")),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "lich_hen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thong_bao",
                        to="lich_hen.lichhen",
                    ),
                ),
                (
                    "nguoi_nhan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thong_bao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Thông báo",
                "verbose_name_plural": "Thông báo",
                "ordering": ["-ngay_tao"],
            },
        ),
    ]
