# Generated by Django 5.2.8 on 2025-12-18 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(verbose_name='Ngày')),
                ('gio_bat_dau', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('gio_ket_thuc', models.TimeField(verbose_name='Giờ kết thúc')),
                ('con_trong', models.BooleanField(default=True, verbose_name='Còn trống')),
                ('bac_si', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_lam_viec', to='accounts.hosobacsi', verbose_name='Bác sĩ')),
            ],
            options={
                'verbose_name': 'Lịch làm việc',
                'verbose_name_plural': 'Lịch làm việc',
                'unique_together': {('bac_si', 'ngay', 'gio_bat_dau')},
            },
        ),
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(verbose_name='Ngày khám')),
                ('gio', models.TimeField(verbose_name='Giờ khám')),
                ('trang_thai', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('approved', 'Đã xác nhận'), ('canceled', 'Đã hủy'), ('completed', 'Hoàn thành')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('trieu_chung', models.TextField(blank=True, verbose_name='Triệu chứng')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('bac_si', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hen', to='accounts.hosobacsi', verbose_name='Bác sĩ')),
                ('benh_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hen', to='accounts.hosobenhnhan', verbose_name='Bệnh nhân')),
                ('lich_lam_viec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hen', to='appointments.lichlamviec', verbose_name='Lịch')),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'ordering': ['-ngay', '-gio'],
            },
        ),
    ]
