# Generated by Django 5.2.8 on 2026-04-18 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChuyenKhoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten",
                    models.CharField(max_length=100, verbose_name="Tên chuyên khoa"),
                ),
                ("mo_ta", models.TextField(blank=True, verbose_name="Mô tả")),
            ],
            options={
                "verbose_name": "Chuyên khoa",
                "verbose_name_plural": "Chuyên khoa",
            },
        ),
        migrations.CreateModel(
            name="HoSoBacSi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mo_ta", models.TextField(blank=True, verbose_name="Mô tả")),
                ("bang_cap", models.CharField(max_length=200, verbose_name="Bằng cấp")),
                (
                    "so_dien_thoai",
                    models.CharField(max_length=15, verbose_name="Số điện thoại"),
                ),
                (
                    "phi_kham",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Phí khám",
                    ),
                ),
                (
                    "anh_dai_dien",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="bac_si/",
                        verbose_name="Ảnh đại diện",
                    ),
                ),
                (
                    "chuyen_khoa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tai_khoan.chuyenkhoa",
                        verbose_name="Chuyên khoa",
                    ),
                ),
                (
                    "nguoi_dung",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ho_so_bac_si",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ bác sĩ",
                "verbose_name_plural": "Hồ sơ bác sĩ",
            },
        ),
        migrations.CreateModel(
            name="HoSoBenhNhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ngay_sinh", models.DateField(verbose_name="Ngày sinh")),
                (
                    "gioi_tinh",
                    models.CharField(
                        choices=[("M", "Nam"), ("F", "Nữ"), ("O", "Khác")],
                        max_length=1,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "so_dien_thoai",
                    models.CharField(max_length=15, verbose_name="Số điện thoại"),
                ),
                ("dia_chi", models.TextField(blank=True, verbose_name="Địa chỉ")),
                (
                    "anh_dai_dien",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="benh_nhan/",
                        verbose_name="Ảnh đại diện",
                    ),
                ),
                (
                    "nguoi_dung",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ho_so_benh_nhan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ bệnh nhân",
                "verbose_name_plural": "Hồ sơ bệnh nhân",
            },
        ),
        migrations.CreateModel(
            name="DanhGiaBacSi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diem_so",
                    models.IntegerField(
                        choices=[
                            (1, "1 sao"),
                            (2, "2 sao"),
                            (3, "3 sao"),
                            (4, "4 sao"),
                            (5, "5 sao"),
                        ],
                        verbose_name="Điểm số",
                    ),
                ),
                ("nhan_xet", models.TextField(blank=True, verbose_name="Nhận xét")),
                (
                    "ngay_danh_gia",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày đánh giá"
                    ),
                ),
                (
                    "bac_si",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danh_gia",
                        to="tai_khoan.hosobacsi",
                    ),
                ),
                (
                    "benh_nhan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danh_gia_da_cho",
                        to="tai_khoan.hosobenhnhan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá bác sĩ",
                "verbose_name_plural": "Đánh giá bác sĩ",
                "unique_together": {("bac_si", "benh_nhan")},
            },
        ),
    ]
