# Generated by Django 5.2.8 on 2026-04-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lich_hen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thuoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_thuoc",
                    models.CharField(max_length=200, verbose_name="Tên thuốc"),
                ),
                (
                    "don_vi",
                    models.CharField(
                        default="viên", max_length=50, verbose_name="Đơn vị"
                    ),
                ),
            ],
            options={
                "verbose_name": "Thuốc",
                "verbose_name_plural": "Thuốc",
            },
        ),
        migrations.CreateModel(
            name="HoSoBenhAn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chan_doan", models.TextField(verbose_name="Chẩn đoán")),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "ngay_tao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "ngay_cap_nhat",
                    models.DateTimeField(auto_now=True, verbose_name="Cập nhật"),
                ),
                (
                    "lich_hen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ho_so_benh_an",
                        to="lich_hen.lichhen",
                        verbose_name="Lịch hẹn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ bệnh án",
                "verbose_name_plural": "Hồ sơ bệnh án",
                "ordering": ["-ngay_tao"],
            },
        ),
        migrations.CreateModel(
            name="ToaThuoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_luong", models.PositiveIntegerField(verbose_name="Số lượng")),
                (
                    "ghi_chu",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ghi chú"
                    ),
                ),
                (
                    "ho_so_benh_an",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toa_thuoc",
                        to="ho_so_benh_an.hosobenhan",
                        verbose_name="Hồ sơ bệnh án",
                    ),
                ),
                (
                    "thuoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ho_so_benh_an.thuoc",
                        verbose_name="Thuốc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Toa thuốc",
                "verbose_name_plural": "Toa thuốc",
            },
        ),
    ]
